version: "3.8"
services:

  # database mysql container
    db:
      container_name: ai_market_local_db
      image: mysql:8.0.30
      networks:
        - ai-market-network
      ports:
        - 3306:3306
      volumes:
        - .conf/conf.d:/etc/mysql/conf.d
      environment:
        MYSQL_DATABASE: ai_market_local
        MYSQL_ROOT_PASSWORD: password

    # reverse proxy container
    envoy:
      build:
        context: .
        dockerfile: ./Dockerfile.envoy
      ports:
        - 9090:9090
        - 9901:9901

    # database firestore container
    # db:
    #   build:
    #     context: .
    #     dockerfile: ./Dockerfile.firestore
    #   ports:
    #     - 8000:8000
    #     - 4000:4000
    #   volumes:
    #     # - .cache/firebase/emulators/:/app/.cache/firebase/emulators/
    #     - .:/app

    # server container
    server:
        build:
          context: .
          target: dev
          dockerfile: ./server/Dockerfile.local
        tty: true
        expose:
            - 8080
        ports:
          - 8080:8080
        environment:
          # PROJECT_ID: foo
          # FIRESTORE_EMULATOR_HOST: host.docker.internal:8000
        command: ["air"]
        volumes:
          - ./server:/go/src/app

    # client container
    client:
        build:
          context: .
          dockerfile: ./Dockerfile.client
        expose:
            - 3000
        ports:
          - 3000:3000    
        command: ["yarn", "start"]
